// GENERATED by scripts/gen-validators.mjs from backend/openapi.json. Do not edit.
import * as v from 'valibot';

export const STATUS_OPTIONS = ["Available","Consumed by build order"] as const;

export const BomLineIn = v.object({
	component_part_id: v.pipe(v.number(), v.integer()),
	quantity: v.number(),
	});
export const BomQtyPatch = v.object({
	quantity: v.number(),
	});
export const BookIn = v.object({
	quantity: v.pipe(v.number(), v.gtValue(0, 'must be greater than 0')),
	});
export const BuildOrderIn = v.object({
	part_id: v.pipe(v.number(), v.integer()),
	quantity: v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0')),
	reference: v.optional(v.string()),
	status: v.optional(v.picklist(["Draft","Pending","Production","Cancelled","Complete"])),
	start_date: v.optional(v.nullable(v.string())),
	end_date: v.optional(v.nullable(v.string())),
	});
export const BuildOrderPatch = v.object({
	quantity: v.optional(v.nullable(v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0')))),
	reference: v.optional(v.nullable(v.string())),
	status: v.optional(v.nullable(v.picklist(["Draft","Pending","Production","Cancelled","Complete"]))),
	start_date: v.optional(v.nullable(v.string())),
	end_date: v.optional(v.nullable(v.string())),
	});
export const NegativeStockIn = v.object({
	part_id: v.pipe(v.number(), v.integer()),
	quantity: v.pipe(v.number(), v.gtValue(0, 'must be greater than 0')),
	build_id: v.pipe(v.number(), v.integer()),
	reason: v.optional(v.string()),
	});
export const POLineIn = v.object({
	supplier_part_id: v.pipe(v.number(), v.integer()),
	quantity: v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0')),
	price: v.optional(v.pipe(v.number(), v.minValue(0))),
	});
export const POLinePatch = v.object({
	quantity: v.optional(v.nullable(v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0')))),
	price: v.optional(v.nullable(v.pipe(v.number(), v.minValue(0)))),
	});
export const PartIn = v.object({
	sku: v.string(),
	description: v.optional(v.string()),
	virtual: v.optional(v.boolean()),
	});
export const PartPatch = v.object({
	sku: v.optional(v.nullable(v.string())),
	description: v.optional(v.nullable(v.string())),
	active: v.optional(v.nullable(v.boolean())),
	assembly: v.optional(v.nullable(v.boolean())),
	virtual: v.optional(v.nullable(v.boolean())),
	purchasable: v.optional(v.nullable(v.boolean())),
	estimated_price: v.optional(v.nullable(v.pipe(v.number(), v.minValue(0)))),
	});
export const ProduceIn = v.object({
	quantity: v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0')),
	});
export const PurchaseOrderIn = v.object({
	supplier_id: v.pipe(v.number(), v.integer()),
	reference: v.optional(v.string()),
	status: v.optional(v.picklist(["Pending","Placed","On Hold","Complete","Cancelled","Lost","Returned"])),
	start_date: v.optional(v.string()),
	end_date: v.optional(v.nullable(v.string())),
	delivery_cost: v.optional(v.number()),
	supplier_reference: v.optional(v.string()),
	});
export const PurchaseOrderPatch = v.object({
	reference: v.optional(v.nullable(v.string())),
	status: v.optional(v.nullable(v.picklist(["Pending","Placed","On Hold","Complete","Cancelled","Lost","Returned"]))),
	start_date: v.optional(v.nullable(v.string())),
	end_date: v.optional(v.nullable(v.string())),
	delivery_cost: v.optional(v.nullable(v.number())),
	supplier_reference: v.optional(v.nullable(v.string())),
	});
export const SettingIn = v.object({
	value: v.string(),
	});
export const StockItemIn = v.object({
	part_id: v.pipe(v.number(), v.integer()),
	});
export const StockItemPatch = v.object({
	count: v.optional(v.nullable(v.number())),
	status: v.optional(v.nullable(v.picklist(["Available","Consumed by build order"]))),
	});
export const StocktakeIn = v.object({
	part_id: v.pipe(v.number(), v.integer()),
	count: v.pipe(v.number(), v.minValue(0)),
	reason: v.string(),
	item_id: v.optional(v.nullable(v.pipe(v.number(), v.integer()))),
	build_id: v.optional(v.nullable(v.pipe(v.number(), v.integer()))),
	po_id: v.optional(v.nullable(v.pipe(v.number(), v.integer()))),
	});
export const SupplierIn = v.object({
	name: v.optional(v.string()),
	});
export const SupplierPartIn = v.object({
	supplier_id: v.pipe(v.number(), v.integer()),
	sku: v.string(),
	part_id: v.pipe(v.number(), v.integer()),
	description: v.optional(v.string()),
	ean: v.optional(v.string()),
	hyperlink: v.optional(v.string()),
	pack_qty: v.optional(v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0'))),
	});
export const SupplierPartPatch = v.object({
	part_id: v.optional(v.nullable(v.pipe(v.number(), v.integer()))),
	description: v.optional(v.nullable(v.string())),
	ean: v.optional(v.nullable(v.string())),
	hyperlink: v.optional(v.nullable(v.string())),
	pack_qty: v.optional(v.nullable(v.pipe(v.number(), v.integer(), v.gtValue(0, 'must be greater than 0')))),
	active: v.optional(v.nullable(v.boolean())),
	});
export const SupplierPatch = v.object({
	name: v.optional(v.nullable(v.string())),
	active: v.optional(v.nullable(v.boolean())),
	});
